name: Run kas for a specific build configuration
inputs:
  machine:
    required: true
  distro_yaml:
    required: true
  distro_name:
    required: true
  target_type:
    description: "Type of the target to build (e.g. base, full)"
    required: true
  target_yaml:
    description: "Path to the target YAML file relative to the distro YAML file"
    required: true
  target_name:
    description: "Name of the target to build"
    required: true
  kernel_yaml:
    required: true
  kernel_dirname:
    required: true
  cache_dir:
    required: true
  use_sstate:
    required: false
    default: "true"
outputs:
  url:
    description: Location of the published binaries
    value: ${{ steps.upload_s3_artifacts.outputs.url }}
runs:
  using: "composite"
  steps:
    # - name: Download kas lockfile
    #   uses: actions/download-artifact@v7
    #   with:
    #     name: kas-lockfile
    #     path: ci/

    - name: Download kas-container
      uses: actions/download-artifact@v7
      with:
         name: kas-container
         path: ${{runner.temp}}

    - name: Setting up kas-container
      shell: bash
      run: |
        KAS_CONTAINER=$RUNNER_TEMP/kas-container
        echo "KAS_CONTAINER=$KAS_CONTAINER" >> $GITHUB_ENV
        chmod +x $KAS_CONTAINER
    
    - name: Setup build variables and sstate-cache
      shell: bash
      run: |
        INPUTS_CACHE_DIR="${{ inputs.cache_dir }}"
        DL_DIR="${INPUTS_CACHE_DIR}/downloads"
        KAS_WORK_DIR="${PWD}/../kas"

        echo "INPUTS_CACHE_DIR=${INPUTS_CACHE_DIR}" >> "$GITHUB_ENV"
        echo "DL_DIR=${DL_DIR}" >> "$GITHUB_ENV"
        echo "KAS_WORK_DIR=${KAS_WORK_DIR}" >> "$GITHUB_ENV"

        echo "Cache directory: ${INPUTS_CACHE_DIR}"
        ls -ald "${INPUTS_CACHE_DIR}"

        if [[ "${{ inputs.use_sstate }}" == "false" ]]; then
          echo "Not using SSTATE cache (full rebuild)."
        else
          # use a single shared sstate cache folder, cleaned up by mtime
          SSTATE_DIR="${INPUTS_CACHE_DIR}/sstate-cache"
          echo "Using SSTATE cache: ${SSTATE_DIR}"
          echo "SSTATE_DIR=${SSTATE_DIR}" >> "$GITHUB_ENV"
        fi
        
        echo "KAS_YAMLS=ci/ci.yml:ci/mirror.yml:ci/${{ inputs.machine }}.yml:${{ inputs.distro_yaml }}:${{ inputs.target_yaml }}:${{ inputs.kernel_yaml }}" >> $GITHUB_ENV

    - name: Dump kas-build yaml
      shell: bash
      run: |
        mkdir -p $KAS_WORK_DIR
        $KAS_CONTAINER dump --resolve-env --resolve-local --resolve-refs ${KAS_YAMLS} > kas-build.yml
        echo "==== kas-build.yml contents start ===="
        cat kas-build.yml
        echo "==== kas-build.yml contents end ===="

    - name: Kas build images and QIR SDK
      shell: bash
      run: |
        $KAS_CONTAINER shell ${KAS_YAMLS} --command "\
        sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends gfortran ccache && \
        bitbake ${{ inputs.target_name }} && bitbake ${{ inputs.target_name }} -c generate_qirp_sdk"

    - name: Kas build images (buildstats)
      shell: bash
      run: |
        ci/kas-container-shell-helper.sh ci/yocto-buildstats.sh
        mv $KAS_WORK_DIR/build/buildstats* .
    
    - name: Stage build artifacts for publishing
      shell: bash
      run: |
        set -x
        # The upload-private-artifact-action runs from a container that
        # expects file to be relative to our PWD. deploy_dir is outside
        # that, so we move things around:
        echo "Current workdir: $(pwd)"
        deploy_dir=../kas/build/tmp/deploy
        images_dir=$deploy_dir/images/${{inputs.machine}}
        uploads_dir=./uploads/${{ inputs.distro_name }}${{ inputs.target_type }}${{ inputs.kernel_dirname }}/${{ inputs.machine }}
        mkdir -p $uploads_dir

        if [ -d $images_dir ]; then
          echo "==== Build image files start ===="
          ls -al $images_dir
          echo "==== Build image files end ===="
          
          find $images_dir/ -maxdepth 1 -type f -exec cp {} $uploads_dir/ \;
          find $images_dir/ -maxdepth 1 -type l \( -name boot-*.img -o -name *.rootfs.ext4.gz -o -name *.rootfs.qcomflash.tar.gz \) -exec cp -d {} $uploads_dir/ \;
        else
          echo "WARNING: No build image files found!"
        fi
        cp -v buildstats* kas-build.yml $uploads_dir/
    
    - name: Stage qirp-sdk artifacts for publishing
      shell: bash
      run: |
        echo "Current workdir: $(pwd)"
        deploy_dir=../kas/build/tmp/deploy
        sdk_dir=$deploy_dir/qirpsdk_artifacts/${{ inputs.machine }}
        uploads_dir=./uploads/${{ inputs.distro_name }}${{ inputs.target_type }}${{ inputs.kernel_dirname }}/${{ inputs.machine }}

        if [ -d $sdk_dir ]; then
          echo "QIRP-SDK files: "
          ls -al $sdk_dir
          mkdir -p $uploads_dir
          find $sdk_dir/ -maxdepth 1 -type f -name "qirp-sdk_*.tar.gz" -printf "%f\n" | xargs tar -czf $uploads_dir/qirp_sdk.tar.gz -C $sdk_dir
        else
          echo "WARNING: No QIRP-SDK files found!"
        fi

    - name: Upload artifacts to S3 bucket
      uses: qualcomm-linux/upload-private-artifact-action@aws-v4
      id: upload_s3_artifacts
      with:
        path: ./uploads
        destination: ${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.run_id }}-${{ github.run_attempt }}/
        s3_bucket: qcom-prd-gh-artifacts

    - name: "Print output"
      shell: bash
      id: print-output
      run: |
        KERNEL_DIRNAME="${{ inputs.kernel_dirname }}"
        BUILDNAME="${{ inputs.machine }}_${{ inputs.distro_name }}${{ inputs.target_type }}${KERNEL_DIRNAME}"
        FILENAME="build-url_${BUILDNAME}"
        echo "${{ steps.upload_s3_artifacts.outputs.url }}" > "${FILENAME}"
        echo "filename=${FILENAME}" >> $GITHUB_OUTPUT
      env:
        INPUTS_KERNEL_DIRNAME: ${{ inputs.kernel_dirname }}
        INPUTS_MACHINE: ${{ inputs.machine }}
        INPUTS_DISTRO_NAME: ${{ inputs.distro_name }}
        
    - name: Upload build URL
      uses: actions/upload-artifact@v6
      with:
        overwrite: true
        name: ${{ steps.print-output.outputs.filename }}
        path: ${{ steps.print-output.outputs.filename }}
