# Copyright (c) 2025 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

require conf/distro/include/qcom-base.inc
require conf/distro/include/qcom-robotics-sdk.inc

require conf/distro/qcom-distro-selinux.conf
require conf/distro/qcom-distro-sota.conf
require conf/distro/qcom-distro-ros2-jazzy.conf

