name: Build on PR
run-name: "${{ github.base_ref }}: ${{ github.event.pull_request.title }}"

on:
  pull_request:
    branches:
      - main
      - wrynose
    paths-ignore:
      - '**/*.md'
      - '.github/.markdownlint.yaml'
  workflow_dispatch:
    inputs:
      use_sstate:
        description: "Use SSTATE cache"
        required: false
        default: "false"

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read
  actions: read

jobs:
  event-file:
    name: "Upload event file"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Event File
        path: ${{ github.event_path }}
  build-pr:
    uses: ./.github/workflows/build-yocto.yml
    with:
      use_sstate: ${{ inputs.use_sstate || 'true' }}
