
name: Build on push

on:
  push:
    branches:
      - main
      - wrynose
  workflow_dispatch:
    inputs:
      use_sstate:
        description: "Use SSTATE cache"
        required: false
        default: "false"

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      packages: read
      actions: read
    uses: $/.github/workflows/build-yocto.yml
    with:
      use_sstate: ${{ inputs.use_sstate || 'true' }}
  test:
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
    uses: $/.github/workflows/test.yml
    needs: [build]
    secrets:
      LAVATOKEN: ${{ secrets.LAVATOKEN }}
    with:
      build_id: ${{ github.run_id }}
